import type { TemplateConfig } from "./types";

export const templates: TemplateConfig[] = [
  {
    id: 'birthday',
    name: 'С Днём Рождения',
    previewImage: '/assets/cards/birthdayTemplateNew.png',
    fields: [
      { id: 'firstName', label: 'Имя', type: 'text', required: true },
      { id: 'lastName', label: 'Фамилия', type: 'text', required: true },
      { id: 'playerNumber', label: 'Номер', type: 'number' },
      { id: 'playerRole', label: 'Амплуа', type: 'role' },
      { id: 'photo', label: 'Фото (при добавлении своего фото заранее удаляйте фон)',
        type: 'player-photo-selector', required: true },
    ],
  },
  {
    id: 'match-day',
    name: 'Матч-день',
    previewImage: '/assets/cards/matchDayTemplateNew.png',
    fields: [
      { id: 'date', label: 'Дата', type: 'custom-date', required: true },
      { id: 'time', label: 'Время', type: 'time', required: true },
      { id: 'location', label: 'Место', type: 'text', required: true },
      { id: 'homeLogo', label: 'Логотип хозяев', type: 'logo-selector', required: true },
      { id: 'awayLogo', label: 'Логотип гостей', type: 'logo-selector', required: true },
      { id: 'photo', label: 'Фото', type: 'image', required: true },
      { id: 'teamVersion', label: 'Команда', type: 'toggle-team', required: true },
    ],
  },
  {
    id: 'score',
    name: 'Счёт игры',
    previewImage: '/assets/cards/scoreTemplate.png',
    fields: [
      { id: 'mainHomeScore', label: 'Счёт домашней команды', type: 'number', required: true },
      { id: 'mainAwayScore', label: 'Счёт команды гостей', type: 'number', required: true },
      { id: 'extraScore', label: 'Cчёт партий (вводим через пробел в формате 00:00 00:00 и т.д)',
        type: 'text', required: true },
      { id: 'homeLogo', label: 'Логотип хозяев', type: 'logo-selector', required: true },
      { id: 'awayLogo', label: 'Логотип гостей', type: 'logo-selector', required: true },
      { id: 'photo', label: 'Фото', type: 'image', required: true },
    ],
  },
  {
    id: 'statistic',
    name: 'Статистика игры',
    previewImage: '/assets/cards/statisticTemplate.png',
    fields: [
      { id: 'mainHomeScore', label: 'Счёт домашней команды', type: 'number', required: true },
      { id: 'mainAwayScore', label: 'Счёт команды гостей', type: 'number', required: true },
      { id: 'extraScore', label: 'Cчёт партий (вводим через пробел в формате 00:00 00:00 и т.д)', type: 'text', required: true },
      { id: 'homeLogo', label: 'Логотип хозяев', type: 'logo-selector', required: true },
      { id: 'awayLogo', label: 'Логотип гостей', type: 'logo-selector', required: true },
      { id: 'homeScores', label: 'Очки домашней команды', type: 'number', required: true },
      { id: 'awayScores', label: 'Очки команды гостей', type: 'number', required: true },
      { id: 'homeAttack', label: 'Атака домашней команды', type: 'number', required: true },
      { id: 'awayAttack', label: 'Атака команды гостей', type: 'number', required: true },
      { id: 'homeBlocks', label: 'Блоки домашней команды', type: 'number', required: true },
      { id: 'awayBlocks', label: 'Блоки команды гостей', type: 'number', required: true },
      { id: 'homeAces', label: 'Эйсы домашней команды', type: 'number', required: true },
      { id: 'awayAces', label: 'Эйсы команды гостей', type: 'number', required: true },
      { id: 'homeTrick', label: 'Приём домашней команды (в процентах: добавить %)', type: 'text', required: true },
      { id: 'awayTrick', label: 'Приём команды гостей (в процентах: добавить %)', type: 'text', required: true },
    ],
  },
  {
    id: 'welcome',
    name: 'Добро пожаловать',
    previewImage: '/assets/cards/welcomeTemplate.png',
    fields: [
      { id: 'firstName', label: 'Имя', type: 'text', required: true },
      { id: 'lastName', label: 'Фамилия', type: 'text', required: true },
      { id: 'homeLogo', label: 'Логотип предыдущей команды', type: 'logo-selector', required: true },
      { id: 'playerRole', label: 'Амплуа', type: 'role' },
      { id: 'photo', label: 'Фото', type: 'image', required: true },
    ],
  },
  {
    id: 'thanks',
    name: 'Спасибо за игру',
    previewImage: '/assets/cards/thanksTemplate.png',
    fields: [
      { id: 'firstName', label: 'Имя', type: 'text', required: true },
      { id: 'lastName', label: 'Фамилия', type: 'text', required: true },
      { id: 'playerNumber', label: 'Номер', type: 'number' },
      { id: 'playerRole', label: 'Амплуа', type: 'role' },
      { id: 'photo', label: 'Фото (при добавлении своего фото заранее удаляйте фон)',
        type: 'player-photo-selector', required: true },
    ],
  },
  {
    id: 'schedule',
    name: 'Расписание на тур',
    previewImage: '/assets/cards/scheduleTemplate.png',
    fields: [
      { id: 'date1', label: 'Дата первой игры', type: 'custom-date', required: true },
      { id: 'date2', label: 'Дата второй игры', type: 'custom-date', required: true },
      { id: 'date3', label: 'Дата третьей игры', type: 'custom-date', required: true },
      { id: 'date4', label: 'Дата четвертой игры', type: 'custom-date', required: true },
      { id: 'teams1', label: 'Команды первой игры (записываем с заглавной буквы через дефис)', type: 'text', required: true},
      { id: 'teams2', label: 'Команды второй игры (записываем с заглавной буквы через дефис)', type: 'text', required: true},
      { id: 'teams3', label: 'Команды третьей игры (записываем с заглавной буквы через дефис)', type: 'text', required: true},
      { id: 'teams4', label: 'Команды четвертой игры (записываем с заглавной буквы через дефис)', type: 'text', required: true},
      { id: 'phrase', label: 'Фраза тура (следите чтобы влезло в строку)', type: 'text', required: true},
      { id: 'location', label: 'Место', type: 'text', required: true },
      { id: 'homeLogo', label: 'Логотип хозяев', type: 'logo-selector' },
      { id: 'awayLogo', label: 'Логотип гостей', type: 'logo-selector', required: true },
      { id: 'photo', label: 'Фото', type: 'image', required: true },
    ],
  },
  {
    id: 'results',
    name: 'Результаты тура',
    previewImage: '/assets/cards/resultsTemplate.png',
    fields: [
      { id: 'mainHomeScore1', label: 'Счёт домашней команды', type: 'number', required: true },
      { id: 'mainAwayScore1', label: 'Счёт команды гостей', type: 'number', required: true },
      { id: 'extraScore1', label: 'Cчёт партий (вводим через пробел в формате 00:00 00:00 и т.д)', type: 'text', required: true },
      { id: 'homeLogo1', label: 'Логотип хозяев', type: 'logo-selector', required: true },
      { id: 'awayLogo1', label: 'Логотип гостей', type: 'logo-selector', required: true },

      { id: 'mainHomeScore2', label: 'Счёт домашней команды', type: 'number', required: true },
      { id: 'mainAwayScore2', label: 'Счёт команды гостей', type: 'number', required: true },
      { id: 'extraScore2', label: 'Cчёт партий (вводим через пробел в формате 00:00 00:00 и т.д)', type: 'text', required: true },
      { id: 'homeLogo2', label: 'Логотип хозяев', type: 'logo-selector', required: true },
      { id: 'awayLogo2', label: 'Логотип гостей', type: 'logo-selector', required: true },

      { id: 'mainHomeScore3', label: 'Счёт домашней команды', type: 'number', required: true },
      { id: 'mainAwayScore3', label: 'Счёт команды гостей', type: 'number', required: true },
      { id: 'extraScore3', label: 'Cчёт партий (вводим через пробел в формате 00:00 00:00 и т.д)', type: 'text', required: true },
      { id: 'homeLogo3', label: 'Логотип хозяев', type: 'logo-selector', required: true },
      { id: 'awayLogo3', label: 'Логотип гостей', type: 'logo-selector', required: true },

      { id: 'mainHomeScore4', label: 'Счёт домашней команды', type: 'number', required: true },
      { id: 'mainAwayScore4', label: 'Счёт команды гостей', type: 'number', required: true },
      { id: 'extraScore4', label: 'Cчёт партий (вводим через пробел в формате 00:00 00:00 и т.д)', type: 'text', required: true },
      { id: 'homeLogo4', label: 'Логотип хозяев', type: 'logo-selector', required: true },
      { id: 'awayLogo4', label: 'Логотип гостей', type: 'logo-selector', required: true },

      { id: 'tour', label: 'Номер тура', type: 'text', required: true},
    ],
  },
];